name: Deploy to Server

on:
  push:
    branches:
      - master  # Or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/dummy-project
            pm2 stop all || true
            git pull origin main
            cd frontend && npm install && npm run build
            cd ../backend && npm install
            pm2 start index.js --name backend
